# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  allowlist_external_dirs:
    - "/config"

recorder:
  purge_keep_days: 60

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
