esphome:
  name: farm-sensors-module
  friendly_name: Farm Sensors Module

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FurLmXyr6M5eQdoRMYUSlg5LTKzSwmeN2ETqT+TaiQ8="

ota:
  password: "170a1e5b74470217226ad246a0386d7a"

wifi:
  # networks:
  # - ssid: !secret wifi_ssid
  # - password: !secret wifi_password

  # - ssid: !secret wifi_ssid2
  # - password: !secret wifi_password2

  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Farm-Sensors-Module"
    password: !secret wifi_ap_password

captive_portal:


sensor:
  - platform: dht
    pin: D2
    temperature:
      name: "Room Temperature"
    humidity:
      name: "Room Humidity"
    update_interval: 60s


  - platform: adc
    pin: A0
    name: "Air quality" 
    update_interval: 60s               
    filters:
      - multiply: 100
    unit_of_measurement: "%"
    icon: "mdi:percent"

  # - platform: pulse_counter
  #   pin: D1
  #   name: "Water Flow Rate"
  #   update_interval: 1s
  #   filters:
  #   - lambda: return (x / 27.0) * 60.0;
  #   unit_of_measurement: "L/hr"  


