esphome:
  name: reservoir-limbs-module
  friendly_name: Reservoir Limbs Module

esp8266:
  board:  d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "TIcZ6RBixiDc1W0xu6wcrlgqSAs1ebgOU77AMpoRWu8="

ota:
  password: "9df54c3058344cfb0c5144158aa29f3e"

wifi:
  # networks:
  # - ssid: !secret wifi_ssid
  # - password: !secret wifi_password

  # - ssid: !secret wifi_ssid2
  # - password: !secret wifi_password2

  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Reservoir-Limbs-Module"
    password: !secret wifi_ap_password1

captive_portal:

switch:
  
  - platform: gpio
    pin: D7
    name: "PH Up Pump"
    inverted: True
    id: ph_up_pump

  - platform: gpio
    pin: D2
    name: "PH Down Pump"
    inverted: True
    id: ph_down_pump

  - platform: gpio
    pin: D5
    name: "TDS Nut A Pump"
    inverted: True
    id: tds_nut_a_pump

  - platform: gpio
    pin: D6
    name: "TDS Nut B Pump"
    inverted: True
    id: tds_nut_b_pump

  - platform: gpio
    pin: D1
    name: "Water Valve"
    inverted: True
    id: water_valve

  