esphome:
  name: reservoir-nose-module
  friendly_name:  Reservoir Nose Module

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "N7orQAxJ3uwzt6iuZbKtSrDcX1tzUbxF9y+JQxB19cc="

ota:
  password: "9c47753ff5d6f1b4d81e4885da403212"

wifi:
  # networks:
  # - ssid: !secret wifi_ssid
  # - password: !secret wifi_password

  # - ssid: !secret wifi_ssid2
  # - password: !secret wifi_password2

  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Reservoir-Nose-Module"
    password: !secret wifi_ap_password2

captive_portal:


switch:
  - platform: gpio
    pin: D1
    name: "Submersible Pump"
    inverted: True
    id: submersible_pump
  - platform: gpio
    pin: D2
    name: "Growlights"
    inverted: True
    id: growlights
    
sensor:
  - platform: ultrasonic
    trigger_pin: D5
    echo_pin: D6
    name: "Water Sensor"
    update_interval: 1s
  - platform: ultrasonic
    trigger_pin: D7
    echo_pin: D8
    name: "NutSol Sensor"
    update_interval: 1s
    